"""Seed: popula o banco com dados de exemplo na primeira execução."""

from app.models import Property, User
from app.security import hash_password

SEED_PROPERTIES = [
    {
        "title": "Casa Moderna com Piscina no Jardim Europa",
        "description": "Casa ampla em condomínio fechado, com 4 suítes, piscina aquecida, jardim privativo e área gourmet completa. Acabamento de alto padrão.",
        "property_type": "Casa",
        "purpose": "comprar",
        "price": 1250000.00,
        "bedrooms": 4,
        "bathrooms": 5,
        "area_sqm": 420,
        "location": "Jardim Europa, São Paulo",
        "neighborhood": "Jardim Europa",
        "city": "São Paulo",
        "state": "SP",
        "image_url": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
        "featured": True,
    },
    {
        "title": "Apartamento Alto Padrão com Vista para o Mar",
        "description": "Apartamento de luxo com 3 suítes, varanda gourmet e vista panorâmica para o mar. Prédio com lazer completo: piscina, academia e salão de festas.",
        "property_type": "Apartamento",
        "purpose": "comprar",
        "price": 980000.00,
        "bedrooms": 3,
        "bathrooms": 4,
        "area_sqm": 180,
        "location": "Orla da Praia, Santos",
        "neighborhood": "Orla da Praia",
        "city": "Santos",
        "state": "SP",
        "image_url": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
        "featured": True,
    },
    {
        "title": "Cobertura Duplex com Terraço Privativo",
        "description": "Cobertura duplex com terraço de 80m², churrasqueira e vista deslumbrante. Localização privilegiada a poucos minutos do metrô.",
        "property_type": "Cobertura",
        "purpose": "comprar",
        "price": 2100000.00,
        "bedrooms": 4,
        "bathrooms": 5,
        "area_sqm": 310,
        "location": "Moema, São Paulo",
        "neighborhood": "Moema",
        "city": "São Paulo",
        "state": "SP",
        "image_url": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
        "featured": True,
    },
    {
        "title": "Terreno 500m² em Condomínio Fechado",
        "description": "Terreno plano de 500m² em condomínio fechado com segurança 24h, infraestrutura completa e área de lazer. Perfeito para construir sua casa dos sonhos.",
        "property_type": "Terreno",
        "purpose": "comprar",
        "price": 350000.00,
        "bedrooms": 0,
        "bathrooms": 0,
        "area_sqm": 500,
        "location": "Alphaville, Barueri",
        "neighborhood": "Alphaville",
        "city": "Barueri",
        "state": "SP",
        "image_url": "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
        "featured": False,
    },
    {
        "title": "Apartamento 2 Quartos com Varanda Encantadora",
        "description": "Apartamento aconchegante com 2 quartos, varanda, vaga de garagem e condomínio com lazer completo. Ótima oportunidade para primeira moradia.",
        "property_type": "Apartamento",
        "purpose": "alugar",
        "price": 2800.00,
        "bedrooms": 2,
        "bathrooms": 2,
        "area_sqm": 68,
        "location": "Pinheiros, São Paulo",
        "neighborhood": "Pinheiros",
        "city": "São Paulo",
        "state": "SP",
        "image_url": "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
        "featured": False,
    },
    {
        "title": "Casa com Jardim no Bairro dos Estados",
        "description": "Casa charmosa com 3 quartos, jardim frontal, quintal espaçoso e garagem para 2 carros. Bairro tranquilo e familiar.",
        "property_type": "Casa",
        "purpose": "alugar",
        "price": 4500.00,
        "bedrooms": 3,
        "bathrooms": 3,
        "area_sqm": 160,
        "location": "Bairro dos Estados, Campinas",
        "neighborhood": "Bairro dos Estados",
        "city": "Campinas",
        "state": "SP",
        "image_url": "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
        "featured": False,
    },
    {
        "title": "Lançamento Studio Mobiliado no Centro",
        "description": "Studio mobiliado de 32m² com design inteligente. Prédio com rooftop, coworking e academia. Perfeito para investidores.",
        "property_type": "Apartamento",
        "purpose": "lancamento",
        "price": 420000.00,
        "bedrooms": 1,
        "bathrooms": 1,
        "area_sqm": 32,
        "location": "Centro, São Paulo",
        "neighborhood": "Centro",
        "city": "São Paulo",
        "state": "SP",
        "image_url": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
        "featured": True,
    },
    {
        "title": "Lançamento Apartamento 3 Quartos com Lazer Premium",
        "description": "Lançamento exclusivo com apartamentos de 3 quartos sendo 1 suíte, varanda e lazer premium: piscina coberta, quadra, playground e espaço gourmet.",
        "property_type": "Apartamento",
        "purpose": "lancamento",
        "price": 750000.00,
        "bedrooms": 3,
        "bathrooms": 3,
        "area_sqm": 120,
        "location": "Vila Olímpia, São Paulo",
        "neighborhood": "Vila Olímpia",
        "city": "São Paulo",
        "state": "SP",
        "image_url": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
        "featured": True,
    },
    {
        "title": "Casa de Campo com Área de Lazer Completa",
        "description": "Casa de campo com 3 suítes, piscina, churrasqueira e 2.000m² de área verde. Perfeita para fins de semana ou moradia.",
        "property_type": "Casa",
        "purpose": "comprar",
        "price": 1650000.00,
        "bedrooms": 3,
        "bathrooms": 4,
        "area_sqm": 380,
        "location": "Bairro das Palmeiras, Campos do Jordão",
        "neighborhood": "Bairro das Palmeiras",
        "city": "Campos do Jordão",
        "state": "SP",
        "image_url": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
        "featured": False,
    },
    {
        "title": "Terreno 800m² com Vista para o Vale",
        "description": "Terreno de 800m² com vista privilegiada para o vale, acesso fácil e documentação em dia. Ótima oportunidade de investimento.",
        "property_type": "Terreno",
        "purpose": "comprar",
        "price": 480000.00,
        "bedrooms": 0,
        "bathrooms": 0,
        "area_sqm": 800,
        "location": "Vale do Sol, Campinas",
        "neighborhood": "Vale do Sol",
        "city": "Campinas",
        "state": "SP",
        "image_url": "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
        "featured": False,
    },
    {
        "title": "Apartamento 1 Quarto Mobiliado Próximo ao Metrô",
        "description": "Apartamento mobiliado de 45m² com 1 quarto, próximo ao metrô e comércios. Ideal para quem busca praticidade no dia a dia.",
        "property_type": "Apartamento",
        "purpose": "alugar",
        "price": 1900.00,
        "bedrooms": 1,
        "bathrooms": 1,
        "area_sqm": 45,
        "location": "Vila Mariana, São Paulo",
        "neighborhood": "Vila Mariana",
        "city": "São Paulo",
        "state": "SP",
        "image_url": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
        "featured": False,
    },
    {
        "title": "Cobertura com Área Gourmet e Vista Incrível",
        "description": "Cobertura com área gourmet de 40m², hidromassagem e vista para a cidade. Mais completa com 3 suítes e vapor.",
        "property_type": "Cobertura",
        "purpose": "comprar",
        "price": 1500000.00,
        "bedrooms": 3,
        "bathrooms": 4,
        "area_sqm": 240,
        "location": "Jardim Paulista, São Paulo",
        "neighborhood": "Jardim Paulista",
        "city": "São Paulo",
        "state": "SP",
        "image_url": "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80",
        "featured": True,
    },
]

SEED_USERS = [
    {"name": "Augusto Silva", "email": "augusto@email.com", "password": "123456"},
]


def seed_if_empty(db) -> None:
    """Cria tabelas e popula com dados de exemplo caso o banco esteja vazio."""
    from app.database import Base, engine
    from app import models  # noqa: F401 - garante o registro dos modelos

    Base.metadata.create_all(bind=engine)

    if db.query(Property).count() == 0:
        for item in SEED_PROPERTIES:
            db.add(Property(**item))
        db.commit()

    if db.query(User).count() == 0:
        for item in SEED_USERS:
            db.add(
                User(
                    name=item["name"],
                    email=item["email"],
                    password=hash_password(item["password"]),
                )
            )
        db.commit()
